### ISSUE TITLE
versión actualizada

### ISSUE THREAD

**Issue by paginasweb** [culqi/culqi-magento#5]
hola, solo para comentarles que hemos actualizado nuestra versión de culqi para Magento v1.9.x, en link es el siguiente:
[magento culqi](http://paginasweb.pe/magento/culqi-magento/)

Saludos

**Comment by heroseven** [comment]
Gracias por avisar!

Atentamente Stephan Vargas Schebesta
*Gerente General*
+51 954462139 (Whatsapp)
www.presla.co

  <https://www.linkedin.com/in/stephanvargasschebesta/>
<https://www.facebook.com/preslaa/>
