### ISSUE TITLE
Magento 2

### ISSUE THREAD

**Issue by jricaldi** [culqi/culqi-magento#6]
Holas, los contenedores de Magento que se puedan crear en AWS solo estan disponibles desde la version 2.0, la version que han actualizado da como para que funcione en estas versiones? #5

**Comment by marti1125** [comment]
@jricaldi actulmente el plugin que tenemos es para la version 1.9 de magento

**Comment by paginasweb** [comment]
Nosotros hemos iniciado el desarrollo del plugin para magento 2.1.x para culqi privadamente, si estas interesado puedes encontrarnos aca: [https://paginasweb.pe/magento/](url) 

PD:va a tomar un par de semanas al menos

**Comment by paginasweb** [comment]
hola Amigos de la comunidad, solo queremos hacerles saber que pueden optar por alquilar una tienda virtual ya integrada con Culqi en la plataforma de Magento 2 en este nuevo dominio [hot sale](https://hotsale.pe)
